const popup = document.createElement("div");
popup.setAttribute("id", "popup");
popup.setAttribute("class", "hide");
popup.innerHTML = '<img src="img/map.svg" usemap="#image-map" />';
popup.innerHTML += `
<!-- Image Map Generated by http://www.image-map.net/ -->
<map name="image-map">
    <area target="_blank" alt="GitHub" title="GitHub" href="https://github.com/tayyebi" coords="37,250,157,310" shape="rect">
    <area target="_blank" alt="Medium" title="Medium" href="https://medium.com/@tayyebi" coords="38,371,158,431" shape="rect">
    <area target="_blank" alt="YouTube" title="YouTube" href="https://youtube.com/c/MohammadRezaTayyebi" coords="38,490,158,550" shape="rect">
    <area target="_blank" alt="Dev Community" title="Dev Community" href="https://dev.to/@tayyebi" coords="37,611,157,671" shape="rect">
    <area target="_blank" alt="MBA Talks" title="MBA Talks" href="https://mbatalks.ir" coords="239,251,359,311" shape="rect">
    <area target="_blank" alt="LinkedIn Newsletter" title="LinkedIn Newsletter" href="https://www.linkedin.com/newsletters/7027132985007030272/" coords="239,370,359,430" shape="rect">
    <area target="_blank" alt="Google Scholar" title="Google Scholar" href="https://scholar.google.com/citations?user=yf6l77sAAAAJ&amp;hl=en&amp;oi=sra" coords="239,490,359,550" shape="rect">
    <area target="_blank" alt="Tayyebi's Book" title="Tayyebi's Book" href="https://tayyebi.github.io/devops-book" coords="238,611,358,671" shape="rect">
    <area target="_blank" alt="TradingView" title="TradingView" href="https://www.tradingview.com/u/tayyebi" coords="437,371,557,431" shape="rect">
    <area target="_blank" alt="Miross" title="Miross" href="https://miross.ir" coords="437,490,557,550" shape="rect">
    <area target="_blank" alt="Gordarg" title="Gordarg" href="https://gordarg.com" coords="638,11,758,71" shape="rect">
    <area target="_blank" alt="Recommendations" title="Recommendation" href="https://kouy.ir/recommendation" coords="638,130,758,189" shape="rect">
    <area target="_blank" alt="P30 Emdad" title="P30 Emdad" href="https://p30emdad.ir" coords="637,570,757,630" shape="rect">
    <area target="_blank" alt="Business Optimization Solutions" title="Business Optimization Solutions" href="https://0pt.ir" coords="637,691,757,751" shape="rect">
    <area target="_blank" alt="Pressez" title="Pressez" href="https://pressz.ir" coords="638,811,758,871" shape="rect">
    <area target="_blank" alt="Sariab Bloggers" title="Sariab Bloggers" href="https://sariab.ir" coords="637,930,757,990" shape="rect">
    <area target="_blank" alt="Resume" title="Resume" href="https://kouy.ir/cv" coords="637,281,757,310" shape="rect">
    <area target="_blank" alt="E-Mail" title="E-Mail" href="mailto:smile@tyyi.net" coords="637,312,757,341" shape="rect">
    <area target="_blank" alt="Phone" title="Phone" href="tel:+989120982276" coords="637,341,757,370" shape="rect">
    <area target="_blank" alt="Calendar" title="Calendar" href="https://calendly.com/tayyebi/meeting" coords="637,371,757,400" shape="rect">
    <area target="_blank" alt="LinkedIn" title="LinkedIn" href="https://www.linkedin.com/in/mohammadrezatayyebi/" coords="637,401,757,430" shape="rect">
    <area target="_blank" alt="Instagram (0nemanband)" title="Instagram (0nemanband)" href="https://instagram.com/0nemanband" coords="438,129,558,191" shape="rect">
</map>
`;

document.body.getElementsByTagName("article")[0].prepend(popup);

function map() {
    var popup = document.getElementById("popup");
    location = "#popup";
    popup.classList.toggle("hide");
}